source 'https://rubygems.org'

gem 'sinatra', '1.4.5'
gem 'sinatra-flash', '0.3.0', require: 'sinatra/flash'
gem 'data_mapper', '1.2.0'
gem 'dm-sqlite-adapter', '1.2.0'
gem 'warden', '1.2.3'
gem 'sqlite3'
gem 'bcrypt'
gem 'haml'